# Generated by Django 5.1.2 on 2024-10-26 16:29

from django.db import migrations
from django.utils import timezone
from decouple import config

class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    def create_superuser(apps, schema_editor):
        from django.contrib.auth import get_user_model
        User = get_user_model()

        if User.objects.exists():
            return
        superuser = User.objects.create_superuser(
            username=config('SUPERUSER_USERNAME'),
            email=config('SUPERUSER_EMAIL'),
            password=config('SUPERUSER_PASSWORD'),
            last_login=timezone.now()
        )
        superuser.save()


    operations = [
        migrations.RunPython(create_superuser)
    ]
